package uy.edu.fing.hpc;

public enum Shift {
    MISSING,

    SUN_MORNING,

    MON_TO_SAT_AFTERNOON,
    SUN_TO_FRI_NIGHT,

    MON_WED_FRI_MORNING,
    MON_WED_FRI_AFTERNOON,
    MON_WED_FRI_NIGHT,

    TUE_THU_SAT_MORNING,
    TUE_THU_SAT_AFTERNOON,
    TUE_THU_SAT_NIGHT,

    SUN_TUE_THU_MORNING,
    SUN_TUE_THU_NIGHT,

    SUN_WED_FRI_AFTERNOON,
}
